url: https://vext2121.github.io/
baseurl: cbreezy.github.io/
title: Chris' Cybersecurity Showcase (In Progress)
description: Here is my collection of cybersecurity projects for all to learn from!
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
